apiVersion: v2
name: vagrantfile-generator
description: A Helm chart for Vagrantfile Generator - web-based tool for generating Vagrantfiles
type: application
version: 0.4.2
appVersion: "1.14.2"
keywords:
    - vagrant
    - vagrantfile
    - generator
    - devops
home: https://github.com/marekruzicka/vagrantfile-generator
maintainers:
    - name: Marek Ruzicka
