# Docker Compose file for Vagrantfile Generator
# Compatible with both Docker and Podman
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: vagrantfile-backend:dev
    container_name: vagrantfile-be-dev
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      # - ./backend/data:/app/data
    command: ["uvicorn", "src.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
    environment:
      - PYTHONPATH=/app
      - CORS_ORIGINS=http://localhost:5173
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 3s
      timeout: 10s
      retries: 3
      start_period: 5s
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile-dev
    image: vagrantfile-frontend:dev
    container_name: vagrantfile-fe-dev
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules  # Prevent host node_modules from overriding container ones
    environment:
      - VITE_API_URL=http://backend:8000
      - VITE_BROWSER_API_URL=http://localhost:8000
      - VITE_ALLOWED_HOSTS=localhost
    depends_on:
      - backend
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://127.0.0.1"]
      interval: 3s
      timeout: 5s
      retries: 3
      start_period: 5s
    restart: unless-stopped

networks:
  default:
    name: vagrantfile-net-dev
