# Update FE_LISTEN_URL to set your frontend URL

x-common-variables: &common-variables
  FE_LISTEN_URL: http://localhost:8080

services:
  backend:
    image: ghcr.io/marekruzicka/vagrantfile-generator-be:latest
    container_name: vgf-be
    environment:
      <<: *common-variables
      CORS_ORIGINS: ${FE_LISTEN_URL}
    volumes:
      - backend-data:/app/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 3s
      timeout: 10s
      retries: 3
      start_period: 5s
    restart: unless-stopped

  frontend:
    image: ghcr.io/marekruzicka/vagrantfile-generator-fe:latest
    container_name: vgf-fe
    environment:
      <<: *common-variables
      FRONTEND_API_URL: ${FRONTEND_API_URL:-/api}
    ports:
      - "8080:80"
    depends_on:
      backend:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://127.0.0.1"]
      interval: 3s
      timeout: 5s
      retries: 3
      start_period: 5s
    restart: unless-stopped

volumes:
  backend-data:
    driver: local

networks:
  default:
    name: vagrantfile-net
