# Docker Compose file for Vagrantfile Generator
# Compatible with both Docker and Podman
# For production, edit environment variables below:
# CORS_ORIGINS=https://yourdomain.com,https://www.yourdomain.com
# VITE_API_URL=https://api.yourdomain.com
# VITE_ALLOWED_HOSTS=yourdomain.com,www.yourdomain.com,1.2.3.4
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: vagrantfile-gen-backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - backend-data:/app/data
    environment:
      - PYTHONPATH=/app
      - CORS_ORIGINS=http://localhost:5173
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: vagrantfile-gen-frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules  # Prevent host node_modules from overriding container ones
    environment:
      - VITE_API_URL=http://localhost:8000
      - VITE_ALLOWED_HOSTS=localhost
    depends_on:
      - backend
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:5173"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped

volumes:
  backend-data:
    driver: local

networks:
  default:
    name: vagrantfile-gen-network