{{- if and .Values.backend.persistence.enabled (not .Values.backend.persistence.existingClaim) }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "vagrantfile-generator.backend.name" . }}-data
  namespace: {{ include "vagrantfile-generator.namespace" . }}
  labels:
    {{- include "vagrantfile-generator.backend.labels" . | nindent 4 }}
  {{- with .Values.backend.persistence.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  accessModes:
    - {{ .Values.backend.persistence.accessMode }}
  {{- if .Values.backend.persistence.storageClass }}
  storageClassName: {{ .Values.backend.persistence.storageClass | quote }}
  {{- end }}
  {{- if .Values.backend.persistence.volumeName }}
  volumeName: {{ .Values.backend.persistence.volumeName | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.backend.persistence.size }}
{{- end }}
